{% set name = "pygeoogc" %}
{% set version = "0.19.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pygeoogc-{{ version }}.tar.gz
  sha256: 1eaf6505728d22d55faa4ee450ab713243ff131c570a23547da5122b657b7e24

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - async-retriever >=0.19.3,<0.20
    - cytoolz
    - defusedxml
    - joblib
    - multidict
    - owslib >=0.27.2
    - pyproj >=3.0.1
    - requests
    - requests-cache >=0.9.6
    - shapely >=2
    - url-normalize >=1.4
    - urllib3
    - yarl

test:
  imports:
    - pygeoogc
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/hyriver/pygeoogc
  summary: An interface to ArcGIS RESTful-, WFS-, and WMS-based services.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - cheginit
